#!/bin/bash
#SBATCH -n 1
#SBATCH -N 1
#SBATCH -t 4320
#SBATCH -p all
#SBATCH --mem=9000
#SBATCH --open-mode=append

#export LBL_HOME=/home/phi.richter/radiative_transfer/lblrtm
module unuse /home/eb/modules/all
module unuse /home/eb/modules/LAMOS
module use /home/eb/modules/_legacy/all
module load Python
module load netcdf4-python
module load matplotlib


mkdir $1
ln -s /home/phi.richter/Code/run_RRTMG/paths_rrtmg $1
ln -s /home/phi.richter/Code/run_RRTMG/keys_sw $1
ln -s /home/phi.richter/Code/run_RRTMG/keys_lw $1
ln -s /home/phi.richter/Code/run_RRTMG/atmosphere $1
python3 run_RRTMG_nudge.py $2 $1

